PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS TASK_AUDIT;
DROP TABLE IF EXISTS TASK_COMMENT;
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS APP_USER;

CREATE TABLE APP_USER (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL UNIQUE,
    PASSWORD_HASH TEXT NOT NULL,
    DISPLAY_NAME TEXT NOT NULL,
    ROLE TEXT NOT NULL CHECK (ROLE IN ('OPERATOR', 'MANAGER')),
    ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0, 1))
);

CREATE TABLE TASK (
    TASK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT,
    STATUS TEXT NOT NULL CHECK (STATUS IN ('OPEN', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'CANCELLED')),
    PRIORITY TEXT NOT NULL CHECK (PRIORITY IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL')),
    OWNER_USER_ID INTEGER,
    CREATED_BY_USER_ID INTEGER NOT NULL,
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT,
    DUE_DATE TEXT,
    FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(USER_ID),
    FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES APP_USER(USER_ID)
);

CREATE TABLE TASK_COMMENT (
    COMMENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TASK_ID INTEGER NOT NULL,
    AUTHOR_USER_ID INTEGER NOT NULL,
    COMMENT_TEXT TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    FOREIGN KEY (TASK_ID) REFERENCES TASK(TASK_ID),
    FOREIGN KEY (AUTHOR_USER_ID) REFERENCES APP_USER(USER_ID)
);

CREATE TABLE TASK_AUDIT (
    AUDIT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TASK_ID INTEGER NOT NULL,
    ACTION TEXT NOT NULL,
    OLD_VALUE TEXT,
    NEW_VALUE TEXT,
    PERFORMED_BY_USER_ID INTEGER NOT NULL,
    PERFORMED_AT TEXT NOT NULL,
    FOREIGN KEY (TASK_ID) REFERENCES TASK(TASK_ID),
    FOREIGN KEY (PERFORMED_BY_USER_ID) REFERENCES APP_USER(USER_ID)
);

CREATE INDEX IDX_TASK_STATUS ON TASK(STATUS);
CREATE INDEX IDX_TASK_PRIORITY ON TASK(PRIORITY);
CREATE INDEX IDX_TASK_OWNER ON TASK(OWNER_USER_ID);
CREATE INDEX IDX_TASK_DUE_DATE ON TASK(DUE_DATE);
CREATE INDEX IDX_COMMENT_TASK ON TASK_COMMENT(TASK_ID);
CREATE INDEX IDX_AUDIT_TASK ON TASK_AUDIT(TASK_ID);
